// Code generated by kratos tool genmc. DO NOT EDIT.

/*
  Package dao is a generated mc cache package.
  It is generated from:
  type _mc interface {
		// mc: -key=keySub -expire=d.demoExpire
		AddCacheSubject(c context.Context, oid int64, sub *model.Subject, tp int8) (err error)
		// mc: -key=keyRp -expire=d.demoExpire
		AddCacheReply(c context.Context, rpid int64, reply *model.Reply) (err error)
	}
*/

package dao

import (
	"context"
	"fmt"

	"github.com/go-kratos/kratos/pkg/cache/memcache"
	"github.com/go-kratos/kratos/pkg/log"
	"reply/internal/model"
)

var _ _mc

// AddCacheSubject Set data to mc
func (d *dao) AddCacheSubject(c context.Context, id int64, val *model.Subject, tp int8) (err error) {
	if val == nil {
		return
	}
	key := keySub(id, tp)
	item := &memcache.Item{Key: key, Object: val, Expiration: d.demoExpire, Flags: memcache.FlagJSON}
	if err = d.mc.Set(c, item); err != nil {
		log.Errorv(c, log.KV("AddCacheSubject", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// AddCacheReply Set data to mc
func (d *dao) AddCacheReply(c context.Context, id int64, val *model.Reply) (err error) {
	if val == nil {
		return
	}
	key := keyRp(id)
	item := &memcache.Item{Key: key, Object: val, Expiration: d.demoExpire, Flags: memcache.FlagJSON}
	if err = d.mc.Set(c, item); err != nil {
		log.Errorv(c, log.KV("AddCacheReply", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}
